# Generated by Django 3.2.7 on 2021-09-16 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0002_law'),
    ]

    operations = [
        migrations.AddField(
            model_name='law',
            name='types_three',
            field=models.IntegerField(choices=[(3, 'Type 3')], max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='law',
            name='types_two',
            field=models.IntegerField(choices=[(2, 'Type 2')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='law',
            name='types',
            field=models.IntegerField(choices=[(1, 'Type 1')], max_length=30),
        ),
    ]
