# Generated by Django 3.2.7 on 2021-09-16 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0003_auto_20210916_0856'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='law',
            name='types_three',
        ),
        migrations.RemoveField(
            model_name='law',
            name='types_two',
        ),
        migrations.AlterField(
            model_name='law',
            name='types',
            field=models.CharField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], max_length=30),
        ),
    ]
