# Generated by Django 3.2.7 on 2021-09-16 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Project', '0005_alter_law_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='law',
            name='types',
            field=models.CharField(choices=[(1, 'Type 1'), (2, 'Type 2'), (3, 'Type 3')], max_length=30, null=True),
        ),
    ]
